name: task
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  cloud_firestore: ^5.4.2
  firebase_core: ^3.5.0
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter_bloc: ^8.1.6
  flutter:
    sdk: flutter
  bloc: ^8.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mocktail: ^1.0.4
  mockito: ^5.4.4
  build_runner: ^2.3.3

flutter:
  uses-material-design: true

import 'package:animated_notch_bottom_bar/animated_notch_bottom_bar/animated_notch_bottom_bar.dart';